server:
  port: 9090
spring:
  application:
    name: curso
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: 1912055897154
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
